### PR TITLE
Account confirmation via SendGrid + custom style for sign-up & reconfirmation pages

### PR DESCRIPTION
**Pull request by danille**
This PR provides changes which are necessary for successful account confirmation on Heroku via integration with SendGrid service. Additionally this PR request delivers some custom styles for `Sign up` and `Resend confirmation code` pages.
This PR fixes issue #12

### CODE REVIEW

**Comment by wzieba** [comment]
Is there any app with following changes possible to view?

**Comment by danille** [comment]
@wzieba, please find link to review app above.

**Comment by danille** [comment]
Rebased on the top of `master` branch.

**Comment by wzieba** [comment]
I was able to perform happy path for user signup, good work 👍

**Pull request merged**
